// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type {
  AddProjectRequest,
  AddProjectResponse,
  AddToRunEvalQueueExamplesResponse,
  AddToRunEvalQueueTracesResponse,
  AddTraceTagsRequest,
  AddTraceTagsResponse,
  BaseScorer,
  CreateDatasetRequest,
  CreateDatasetResponse,
  CustomScorerExistsResponse,
  DatasetInfo,
  DeleteProjectResponse,
  E2EFetchSpanScoreRequest,
  E2EFetchSpanScoreResponse,
  E2EFetchTraceRequest,
  E2EFetchTraceResponse,
  ErrorResponse,
  Example,
  ExampleEvaluationRun,
  ExampleScoringResult,
  ExperimentRunItem,
  ExperimentScorer,
  FetchExperimentRunResponse,
  FetchPromptResponse,
  FetchPromptScorersResponse,
  GetPromptVersionsResponse,
  HealthResponse,
  InsertExamplesRequest,
  InsertExamplesResponse,
  InsertPromptRequest,
  InsertPromptResponse,
  LogEvalResultsRequest,
  LogEvalResultsResponse,
  PromptCommitInfo,
  PromptScorer,
  PullAllDatasetsResponse,
  PullDatasetResponse,
  ResolveProjectRequest,
  ResolveProjectResponse,
  ScorerConfig,
  ScorerExistsResponse,
  ScoringResult,
  TagPromptRequest,
  TagPromptResponse,
  TraceEvaluationRun,
  TraceInfo,
  TraceScoringResult,
  TraceSpan,
  TriggerRootSpanRulesRequest,
  TriggerRootSpanRulesResponse,
  UntagPromptRequest,
  UntagPromptResponse,
  UploadCustomScorerRequest,
  UploadCustomScorerResponse,
  WelcomeResponse,
} from "./types";

export class JudgmentApiClient {
  private baseUrl: string;
  private apiKey: string;
  private organizationId: string;

  constructor(baseUrl: string, apiKey: string, organizationId: string) {
    this.baseUrl = baseUrl;
    this.apiKey = apiKey;
    this.organizationId = organizationId;
  }

  getBaseUrl(): string {
    return this.baseUrl;
  }
  getApiKey(): string {
    return this.apiKey;
  }
  getOrganizationId(): string {
    return this.organizationId;
  }

  private async request<T>(
    method: string,
    url: string,
    body?: unknown,
  ): Promise<T> {
    const response = await fetch(url, {
      method,
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.apiKey}`,
        "X-Organization-Id": this.organizationId,
      },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!response.ok) {
      const text = await response.text();
      throw new Error(`HTTP ${response.status}: ${text}`);
    }
    return response.json() as T;
  }

  async postOtelV1traces(): Promise<unknown> {
    const url = this.baseUrl + "/otel/v1/traces";
    return this.request("POST", url, {});
  }

  async postOtelTriggerRootSpanRules(
    payload: TriggerRootSpanRulesRequest,
  ): Promise<TriggerRootSpanRulesResponse> {
    const url = this.baseUrl + "/otel/trigger_root_span_rules";
    return this.request("POST", url, payload);
  }

  async postV1projectsResolve(
    payload: ResolveProjectRequest,
  ): Promise<ResolveProjectResponse> {
    const url = this.baseUrl + "/v1/projects/resolve/";
    return this.request("POST", url, payload);
  }

  async postV1projects(
    payload: AddProjectRequest,
  ): Promise<AddProjectResponse> {
    const url = this.baseUrl + "/v1/projects";
    return this.request("POST", url, payload);
  }

  async deleteV1projects(projectId: string): Promise<DeleteProjectResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}`;
    return this.request("DELETE", url, {});
  }

  async postV1projectsDatasets(
    projectId: string,
    payload: CreateDatasetRequest,
  ): Promise<CreateDatasetResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/datasets`;
    return this.request("POST", url, payload);
  }

  async getV1projectsDatasets(
    projectId: string,
  ): Promise<PullAllDatasetsResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/datasets`;
    return this.request("GET", url, undefined);
  }

  async postV1projectsDatasetsByDatasetNameExamples(
    projectId: string,
    datasetName: string,
    payload: InsertExamplesRequest,
  ): Promise<InsertExamplesResponse> {
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/datasets/${datasetName}/examples`;
    return this.request("POST", url, payload);
  }

  async getV1projectsDatasetsByDatasetName(
    projectId: string,
    datasetName: string,
  ): Promise<PullDatasetResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/datasets/${datasetName}`;
    return this.request("GET", url, undefined);
  }

  async postV1projectsEvaluateExamples(
    projectId: string,
    payload: ExampleEvaluationRun,
  ): Promise<unknown> {
    const url = this.baseUrl + `/v1/projects/${projectId}/evaluate/examples`;
    return this.request("POST", url, payload);
  }

  async postV1projectsEvaluateTraces(
    projectId: string,
    payload: TraceEvaluationRun,
  ): Promise<unknown> {
    const url = this.baseUrl + `/v1/projects/${projectId}/evaluate/traces`;
    return this.request("POST", url, payload);
  }

  async postV1projectsEvalResults(
    projectId: string,
    payload: LogEvalResultsRequest,
  ): Promise<LogEvalResultsResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/eval-results`;
    return this.request("POST", url, payload);
  }

  async getV1projectsExperimentsByRunId(
    projectId: string,
    runId: string,
  ): Promise<FetchExperimentRunResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/experiments/${runId}`;
    return this.request("GET", url, undefined);
  }

  async postV1projectsEvalQueueExamples(
    projectId: string,
    payload: ExampleEvaluationRun,
  ): Promise<AddToRunEvalQueueExamplesResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/eval-queue/examples`;
    return this.request("POST", url, payload);
  }

  async postV1projectsEvalQueueTraces(
    projectId: string,
    payload: TraceEvaluationRun,
  ): Promise<AddToRunEvalQueueTracesResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/eval-queue/traces`;
    return this.request("POST", url, payload);
  }

  async getV1projectsPromptsByName(
    projectId: string,
    name: string,
    commit_id?: string,
    tag?: string,
  ): Promise<FetchPromptResponse> {
    const params = new URLSearchParams();
    if (commit_id !== undefined) params.set("commit_id", commit_id);
    if (tag !== undefined) params.set("tag", tag);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/prompts/${name}` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async postV1projectsPrompts(
    projectId: string,
    payload: InsertPromptRequest,
  ): Promise<InsertPromptResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/prompts`;
    return this.request("POST", url, payload);
  }

  async postV1projectsPromptsByNameTags(
    projectId: string,
    name: string,
    payload: TagPromptRequest,
  ): Promise<TagPromptResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/prompts/${name}/tags`;
    return this.request("POST", url, payload);
  }

  async deleteV1projectsPromptsByNameTags(
    projectId: string,
    name: string,
    payload: UntagPromptRequest,
  ): Promise<UntagPromptResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/prompts/${name}/tags`;
    return this.request("DELETE", url, payload);
  }

  async getV1projectsPromptsByNameVersions(
    projectId: string,
    name: string,
  ): Promise<GetPromptVersionsResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/prompts/${name}/versions`;
    return this.request("GET", url, undefined);
  }

  async getV1projectsScorers(
    projectId: string,
    names?: string,
    is_trace?: string,
  ): Promise<FetchPromptScorersResponse> {
    const params = new URLSearchParams();
    if (names !== undefined) params.set("names", names);
    if (is_trace !== undefined) params.set("is_trace", is_trace);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/scorers` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async getV1projectsScorersByNameExists(
    projectId: string,
    name: string,
  ): Promise<ScorerExistsResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/scorers/${name}/exists`;
    return this.request("GET", url, undefined);
  }

  async postV1projectsScorersCustom(
    projectId: string,
    payload: UploadCustomScorerRequest,
  ): Promise<UploadCustomScorerResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/scorers/custom`;
    return this.request("POST", url, payload);
  }

  async getV1projectsScorersCustomByNameExists(
    projectId: string,
    name: string,
  ): Promise<CustomScorerExistsResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/scorers/custom/${name}/exists`;
    return this.request("GET", url, undefined);
  }

  async postV1projectsTracesByTraceIdTags(
    projectId: string,
    traceId: string,
    payload: AddTraceTagsRequest,
  ): Promise<AddTraceTagsResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/traces/${traceId}/tags`;
    return this.request("POST", url, payload);
  }

  async postV1e2eFetchTrace(
    payload: E2EFetchTraceRequest,
  ): Promise<E2EFetchTraceResponse> {
    const url = this.baseUrl + "/v1/e2e_fetch_trace/";
    return this.request("POST", url, payload);
  }

  async postV1e2eFetchSpanScore(
    payload: E2EFetchSpanScoreRequest,
  ): Promise<E2EFetchSpanScoreResponse> {
    const url = this.baseUrl + "/v1/e2e_fetch_span_score/";
    return this.request("POST", url, payload);
  }
}
