// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type {
  AddDatasetItemsResponse,
  AddProjectRequest,
  AddProjectResponse,
  AddToRunEvalQueueExamplesResponse,
  AddToRunEvalQueueTracesResponse,
  AddTraceTagsRequest,
  AddTraceTagsResponse,
  ApplyTestRunSuccessRequest,
  ApplyTestRunSuccessResponse,
  CreateOfflineDatasetRequest,
  CreateOfflineDatasetResponse,
  CreateTestConfigRequest,
  CreateTestRunRequest,
  CustomScorerExistsResponse,
  DeleteOfflineDatasetResponse,
  DeleteProjectResponse,
  DeleteTestConfigResponse,
  E2EFetchSpanScoreRequest,
  E2EFetchSpanScoreResponse,
  E2EFetchTraceResponse,
  ExampleEvaluationRun,
  FetchPromptResponse,
  FetchPromptScorersResponse,
  FetchTestRunViaExperimentAliasResponse,
  GetPromptVersionsResponse,
  InsertOfflineDatasetExamplesRequest,
  InsertPromptRequest,
  InsertPromptResponse,
  OfflineDatasetPageResponse,
  OfflineDatasetVersionsResponse,
  OfflineTestsLogEvalResultsExamplesRequest,
  OfflineTestsLogEvalResultsExamplesResponse,
  OfflineTestsLogEvalResultsRequest,
  OfflineTestsLogEvalResultsResponse,
  PreparedTestRunResponse,
  PullAllOfflineDatasetsResponse,
  PullOfflineDatasetResponse,
  ResolveProjectRequest,
  ResolveProjectResponse,
  SDKCreateAgentJudgeRequest,
  SDKCreateAgentJudgeResponse,
  SDKUpdateAgentJudgeRequest,
  SDKUpdateAgentJudgeResponse,
  ScorerExistsResponse,
  TagPromptRequest,
  TagPromptResponse,
  TestConfigResponse,
  TestConfigsResponse,
  TestRunGraphResponse,
  TestRunItemsResponse,
  TestRunResponse,
  TestRunsResponse,
  TraceEvaluationRun,
  UntagPromptRequest,
  UntagPromptResponse,
  UpdateTestConfigRequest,
  UpdateTestRunStatusRequest,
  UploadCustomScorerResponse,
} from "./models";

export class JudgmentApiClient {
  private baseUrl: string;
  private apiKey: string;
  private organizationId: string;

  constructor(baseUrl: string, apiKey: string, organizationId: string) {
    this.baseUrl = baseUrl;
    this.apiKey = apiKey;
    this.organizationId = organizationId;
  }

  getBaseUrl(): string {
    return this.baseUrl;
  }
  getApiKey(): string {
    return this.apiKey;
  }
  getOrganizationId(): string {
    return this.organizationId;
  }

  private async request<T>(
    method: string,
    url: string,
    body?: unknown,
  ): Promise<T> {
    const response = await fetch(url, {
      method,
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.apiKey}`,
        "X-Organization-Id": this.organizationId,
      },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!response.ok) {
      const text = await response.text();
      throw new Error(`HTTP ${response.status}: ${text}`);
    }
    return response.json() as T;
  }

  async postOtelV1traces(): Promise<unknown> {
    const url = this.baseUrl + "/otel/v1/traces";
    return this.request("POST", url, {});
  }

  async postOtelV1offlineTraces(): Promise<unknown> {
    const url = this.baseUrl + "/otel/v1/offline-traces";
    return this.request("POST", url, {});
  }

  async postV1projectsResolve(
    payload: ResolveProjectRequest,
  ): Promise<ResolveProjectResponse> {
    const url = this.baseUrl + "/v1/projects/resolve/";
    return this.request("POST", url, payload);
  }

  async postV1projects(
    payload: AddProjectRequest,
  ): Promise<AddProjectResponse> {
    const url = this.baseUrl + "/v1/projects";
    return this.request("POST", url, payload);
  }

  async deleteV1projects(projectId: string): Promise<DeleteProjectResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}`;
    return this.request("DELETE", url, {});
  }

  async postV1projectsDatasets(
    projectId: string,
    payload: CreateOfflineDatasetRequest,
  ): Promise<CreateOfflineDatasetResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/datasets`;
    return this.request("POST", url, payload);
  }

  async getV1projectsDatasets(
    projectId: string,
  ): Promise<PullAllOfflineDatasetsResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/datasets`;
    return this.request("GET", url, undefined);
  }

  async getV1projectsDatasetsByDatasetIdentifierVersions(
    projectId: string,
    datasetIdentifier: string,
  ): Promise<OfflineDatasetVersionsResponse> {
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/datasets/${datasetIdentifier}/versions`;
    return this.request("GET", url, undefined);
  }

  async getV1projectsDatasetsByDatasetIdentifierPage(
    projectId: string,
    datasetIdentifier: string,
    version?: string,
    limit?: string,
    cursor_created_at?: string,
    cursor_example_id?: string,
  ): Promise<OfflineDatasetPageResponse> {
    const params = new URLSearchParams();
    if (version !== undefined) params.set("version", version);
    if (limit !== undefined) params.set("limit", limit);
    if (cursor_created_at !== undefined)
      params.set("cursor_created_at", cursor_created_at);
    if (cursor_example_id !== undefined)
      params.set("cursor_example_id", cursor_example_id);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/datasets/${datasetIdentifier}/page` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async postV1projectsDatasetsByDatasetIdentifierExamples(
    projectId: string,
    datasetIdentifier: string,
    payload: InsertOfflineDatasetExamplesRequest,
  ): Promise<AddDatasetItemsResponse> {
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/datasets/${datasetIdentifier}/examples`;
    return this.request("POST", url, payload);
  }

  async deleteV1projectsDatasetsByDatasetIdentifier(
    projectId: string,
    datasetIdentifier: string,
  ): Promise<DeleteOfflineDatasetResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/datasets/${datasetIdentifier}`;
    return this.request("DELETE", url, {});
  }

  async getV1projectsDatasetsByDatasetIdentifier(
    projectId: string,
    datasetIdentifier: string,
  ): Promise<PullOfflineDatasetResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/datasets/${datasetIdentifier}`;
    return this.request("GET", url, undefined);
  }

  async getV1projectsTestConfigs(
    projectId: string,
    dataset_id?: string,
  ): Promise<TestConfigsResponse> {
    const params = new URLSearchParams();
    if (dataset_id !== undefined) params.set("dataset_id", dataset_id);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/test-configs` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async postV1projectsTestConfigs(
    projectId: string,
    payload: CreateTestConfigRequest,
  ): Promise<TestConfigResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/test-configs`;
    return this.request("POST", url, payload);
  }

  async getV1projectsTestConfigsByTestConfigId(
    projectId: string,
    testConfigId: string,
  ): Promise<TestConfigResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/test-configs/${testConfigId}`;
    return this.request("GET", url, undefined);
  }

  async patchV1projectsTestConfigsByTestConfigId(
    projectId: string,
    testConfigId: string,
    payload: UpdateTestConfigRequest,
  ): Promise<TestConfigResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/test-configs/${testConfigId}`;
    return this.request("PATCH", url, payload);
  }

  async deleteV1projectsTestConfigsByTestConfigId(
    projectId: string,
    testConfigId: string,
  ): Promise<DeleteTestConfigResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/test-configs/${testConfigId}`;
    return this.request("DELETE", url, {});
  }

  async getV1projectsTestRuns(
    projectId: string,
    test_config_id?: string,
    dataset_id?: string,
    status?: string,
    limit?: string,
  ): Promise<TestRunsResponse> {
    const params = new URLSearchParams();
    if (test_config_id !== undefined)
      params.set("test_config_id", test_config_id);
    if (dataset_id !== undefined) params.set("dataset_id", dataset_id);
    if (status !== undefined) params.set("status", status);
    if (limit !== undefined) params.set("limit", limit);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/test-runs` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async postV1projectsTestRuns(
    projectId: string,
    payload: CreateTestRunRequest,
  ): Promise<PreparedTestRunResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/test-runs`;
    return this.request("POST", url, payload);
  }

  async getV1projectsTestRunsByTestRunId(
    projectId: string,
    testRunId: string,
  ): Promise<TestRunResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/test-runs/${testRunId}`;
    return this.request("GET", url, undefined);
  }

  async patchV1projectsTestRunsByTestRunIdStatus(
    projectId: string,
    testRunId: string,
    payload: UpdateTestRunStatusRequest,
  ): Promise<TestRunResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/test-runs/${testRunId}/status`;
    return this.request("PATCH", url, payload);
  }

  async patchV1projectsTestRunsByTestRunIdSuccess(
    projectId: string,
    testRunId: string,
    payload: ApplyTestRunSuccessRequest,
  ): Promise<ApplyTestRunSuccessResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/test-runs/${testRunId}/success`;
    return this.request("PATCH", url, payload);
  }

  async getV1projectsTestRunsByTestRunIdItems(
    projectId: string,
    testRunId: string,
    limit?: string,
    cursor?: string,
  ): Promise<TestRunItemsResponse> {
    const params = new URLSearchParams();
    if (limit !== undefined) params.set("limit", limit);
    if (cursor !== undefined) params.set("cursor", cursor);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/test-runs/${testRunId}/items` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async getV1projectsTestRunsByTestRunIdResults(
    projectId: string,
    testRunId: string,
    limit?: string,
    cursor?: string,
  ): Promise<TestRunItemsResponse> {
    const params = new URLSearchParams();
    if (limit !== undefined) params.set("limit", limit);
    if (cursor !== undefined) params.set("cursor", cursor);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/test-runs/${testRunId}/results` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async getV1projectsTestRunsByTestRunIdGraph(
    projectId: string,
    testRunId: string,
  ): Promise<TestRunGraphResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/test-runs/${testRunId}/graph`;
    return this.request("GET", url, undefined);
  }

  async getV1projectsExperimentsByRunId(
    projectId: string,
    runId: string,
    limit?: string,
    cursor?: string,
  ): Promise<FetchTestRunViaExperimentAliasResponse> {
    const params = new URLSearchParams();
    if (limit !== undefined) params.set("limit", limit);
    if (cursor !== undefined) params.set("cursor", cursor);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/experiments/${runId}` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async postV1projectsEvalResults(
    projectId: string,
    payload: OfflineTestsLogEvalResultsRequest,
  ): Promise<OfflineTestsLogEvalResultsResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/eval-results`;
    return this.request("POST", url, payload);
  }

  async postV1projectsEvalResultsExamples(
    projectId: string,
    payload: OfflineTestsLogEvalResultsExamplesRequest,
  ): Promise<OfflineTestsLogEvalResultsExamplesResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/eval-results/examples`;
    return this.request("POST", url, payload);
  }

  async postV1projectsEvaluateExamples(
    projectId: string,
    payload: ExampleEvaluationRun,
  ): Promise<unknown> {
    const url = this.baseUrl + `/v1/projects/${projectId}/evaluate/examples`;
    return this.request("POST", url, payload);
  }

  async postV1projectsEvaluateTraces(
    projectId: string,
    payload: TraceEvaluationRun,
  ): Promise<unknown> {
    const url = this.baseUrl + `/v1/projects/${projectId}/evaluate/traces`;
    return this.request("POST", url, payload);
  }

  async postV1projectsEvalQueueExamples(
    projectId: string,
    payload: ExampleEvaluationRun,
  ): Promise<AddToRunEvalQueueExamplesResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/eval-queue/examples`;
    return this.request("POST", url, payload);
  }

  async postV1projectsEvalQueueTraces(
    projectId: string,
    payload: TraceEvaluationRun,
  ): Promise<AddToRunEvalQueueTracesResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/eval-queue/traces`;
    return this.request("POST", url, payload);
  }

  async getV1projectsPromptsByName(
    projectId: string,
    name: string,
    commit_id?: string,
    tag?: string,
  ): Promise<FetchPromptResponse> {
    const params = new URLSearchParams();
    if (commit_id !== undefined) params.set("commit_id", commit_id);
    if (tag !== undefined) params.set("tag", tag);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/prompts/${name}` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async postV1projectsPrompts(
    projectId: string,
    payload: InsertPromptRequest,
  ): Promise<InsertPromptResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/prompts`;
    return this.request("POST", url, payload);
  }

  async postV1projectsPromptsByNameTags(
    projectId: string,
    name: string,
    payload: TagPromptRequest,
  ): Promise<TagPromptResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/prompts/${name}/tags`;
    return this.request("POST", url, payload);
  }

  async deleteV1projectsPromptsByNameTags(
    projectId: string,
    name: string,
    payload: UntagPromptRequest,
  ): Promise<UntagPromptResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/prompts/${name}/tags`;
    return this.request("DELETE", url, payload);
  }

  async getV1projectsPromptsByNameVersions(
    projectId: string,
    name: string,
  ): Promise<GetPromptVersionsResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/prompts/${name}/versions`;
    return this.request("GET", url, undefined);
  }

  async getV1projectsScorers(
    projectId: string,
    names?: string,
    is_trace?: string,
  ): Promise<FetchPromptScorersResponse> {
    const params = new URLSearchParams();
    if (names !== undefined) params.set("names", names);
    if (is_trace !== undefined) params.set("is_trace", is_trace);
    const url =
      this.baseUrl +
      `/v1/projects/${projectId}/scorers` +
      (params.toString() ? "?" + params.toString() : "");
    return this.request("GET", url, undefined);
  }

  async getV1projectsScorersByNameExists(
    projectId: string,
    name: string,
  ): Promise<ScorerExistsResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/scorers/${name}/exists`;
    return this.request("GET", url, undefined);
  }

  async postV1projectsScorersCustom(projectId: string): Promise<unknown> {
    const url = this.baseUrl + `/v1/projects/${projectId}/scorers/custom`;
    return this.request("POST", url, {});
  }

  async postV1projectsScorersCustomBundle(
    projectId: string,
  ): Promise<UploadCustomScorerResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/scorers/custom/bundle`;
    return this.request("POST", url, {});
  }

  async getV1projectsScorersCustomByNameExists(
    projectId: string,
    name: string,
  ): Promise<CustomScorerExistsResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/scorers/custom/${name}/exists`;
    return this.request("GET", url, undefined);
  }

  async postV1projectsTracesByTraceIdTags(
    projectId: string,
    traceId: string,
    payload: AddTraceTagsRequest,
  ): Promise<AddTraceTagsResponse> {
    const url =
      this.baseUrl + `/v1/projects/${projectId}/traces/${traceId}/tags`;
    return this.request("POST", url, payload);
  }

  async getV1e2eFetchTraceByProjectNameByTraceId(
    projectName: string,
    traceId: string,
  ): Promise<E2EFetchTraceResponse> {
    const url = this.baseUrl + `/v1/e2e_fetch_trace/${projectName}/${traceId}`;
    return this.request("GET", url, undefined);
  }

  async getV1e2eTracesPerProject(projectId: string): Promise<unknown> {
    const url = this.baseUrl + `/v1/e2e_traces_per_project/${projectId}`;
    return this.request("GET", url, undefined);
  }

  async postV1e2eFetchSpanScore(
    payload: E2EFetchSpanScoreRequest,
  ): Promise<E2EFetchSpanScoreResponse> {
    const url = this.baseUrl + "/v1/e2e_fetch_span_score/";
    return this.request("POST", url, payload);
  }

  async postV1projectsJudges(
    projectId: string,
    payload: SDKCreateAgentJudgeRequest,
  ): Promise<SDKCreateAgentJudgeResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/judges`;
    return this.request("POST", url, payload);
  }

  async patchV1projectsJudgesByJudgeId(
    projectId: string,
    judgeId: string,
    payload: SDKUpdateAgentJudgeRequest,
  ): Promise<SDKUpdateAgentJudgeResponse> {
    const url = this.baseUrl + `/v1/projects/${projectId}/judges/${judgeId}`;
    return this.request("PATCH", url, payload);
  }
}
