// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface AddProjectRequest {
  project_name: string;
}

export interface AddProjectResponse {
  project_id: string;
}

export interface AddToRunEvalQueueExamplesResponse {
  success: boolean;
  status: string;
  message: string;
}

export interface AddToRunEvalQueueTracesResponse {
  success: boolean;
  status: string;
  message: string;
}

export interface AddTraceTagsRequest {
  tags: string[];
}

export interface AddTraceTagsResponse {
  success: boolean;
}

export interface BaseScorer {
  score_type: string;
  name?: string | null | null;
  class_name?: string | null | null;
  score?: number | null | null;
  minimum_score_range?: number | null;
  maximum_score_range?: number | null;
  score_breakdown?: Record<string, unknown> | null | null;
  reason?: (string | Record<string, unknown>) | null;
  success?: boolean | null | null;
  model?: string | null | null;
  error?: string | null | null;
  additional_metadata?: Record<string, unknown> | null | null;
  user?: string | null | null;
  server_hosted?: boolean | null | null;
  using_native_model?: boolean | null | null;
  required_params?: string[] | null | null;
  strict_mode?: boolean | null | null;
}

export interface CreateDatasetRequest {
  name: string;
  dataset_kind: string;
  examples: Example[];
  overwrite: boolean;
}

export interface CreateDatasetResponse {
  detail: string;
}

export interface CustomScorerExistsResponse {
  exists: boolean;
}

export interface DatasetInfo {
  dataset_id: string;
  name: string;
  created_at: string;
  kind: string;
  entries: number;
  creator: string;
}

export interface DeleteProjectResponse {
  status: string;
  message: string;
}

export interface E2EFetchSpanScoreRequest {
  project_name: string;
  trace_id: string;
  span_id: string;
}

export type E2EFetchSpanScoreResponse = Record<string, unknown>[];

export interface E2EFetchTraceRequest {
  project_name: string;
  trace_id: string;
}

export type E2EFetchTraceResponse = Record<string, unknown>[];

export interface ErrorResponse {
  error: string;
  message?: string | null;
}

export interface Example {
  example_id: string;
  created_at: string;
  name?: string | null | null;
}

export interface ExampleEvaluationRun {
  id?: string | null | null;
  project_id: string;
  eval_name: string;
  model?: string | null | null;
  created_at?: string | null | null;
  user_id?: string | null;
  scorers?: Record<string, unknown>[] | null | null;
  custom_scorers: BaseScorer[];
  judgment_scorers: ScorerConfig[];
  examples: Example[];
  trace_span_id?: string | null | null;
  trace_id?: string | null | null;
}

export interface ExampleScoringResult {
  scorers_data: Record<string, unknown>[];
  name?: string | null | null;
  data_object: Example;
  trace_id?: string | null | null;
  run_duration?: number | null | null;
  evaluation_cost?: number | null | null;
}

export interface ExperimentRunItem {
  organization_id: string;
  experiment_run_id: string;
  example_id: string;
  data: Record<string, unknown>;
  name: string | null;
  created_at: string;
  scorers: ExperimentScorer[];
}

export interface ExperimentScorer {
  scorer_data_id: string;
  name: string;
  score: number;
  success: number;
  reason: string | null;
  evaluation_model: string | null;
  threshold: number;
  created_at: string;
  error: string | null;
  additional_metadata: Record<string, unknown> | null;
  minimum_score_range: number;
  maximum_score_range: number;
}

export interface FetchExperimentRunResponse {
  results: ExperimentRunItem[] | null;
  ui_results_url: string | null;
}

export interface FetchPromptResponse {
  commit: PromptCommitInfo | null;
}

export interface FetchPromptScorersResponse {
  scorers: PromptScorer[];
}

export interface GetPromptVersionsResponse {
  versions: PromptCommitInfo[];
}

export interface HealthResponse {
  status: string;
  timestamp: string;
}

export interface InsertExamplesRequest {
  examples: Example[];
}

export interface InsertExamplesResponse {
  detail: string;
}

export interface InsertPromptRequest {
  name: string;
  prompt: string;
  tags?: string[] | null;
}

export interface InsertPromptResponse {
  commit_id: string;
  parent_commit_id: string | null;
  created_at: string;
}

export interface LogEvalResultsRequest {
  results: ScoringResult[];
  run: ExampleEvaluationRun;
}

export interface LogEvalResultsResponse {
  ui_results_url: string;
}

export interface PromptCommitInfo {
  name: string;
  prompt: string;
  tags: string[];
  commit_id: string;
  parent_commit_id: string | null;
  created_at: string;
  first_name: string;
  last_name: string;
  user_email: string;
}

export interface PromptScorer {
  id: string;
  user_id: string;
  organization_id: string;
  name: string;
  prompt: string;
  threshold: number;
  model: string;
  options?: Record<string, unknown> | null | null;
  description?: string | null | null;
  created_at: string | null;
  updated_at: string | null;
  is_trace?: boolean | null;
}

export type PullAllDatasetsResponse = DatasetInfo[];

export interface PullDatasetResponse {
  name: string;
  project_id: string;
  dataset_kind: string;
  examples: Example[];
}

export interface ResolveProjectRequest {
  project_name: string;
}

export interface ResolveProjectResponse {
  project_id: string;
}

export interface ScorerConfig {
  score_type: string;
  name?: string | null | null;
  threshold: number;
  model?: string | null | null;
  required_params?: string[] | null | null;
  kwargs?: Record<string, unknown> | null | null;
  result_type?: string | null;
}

export interface ScorerExistsResponse {
  exists: boolean;
}

export interface ScoringResult {
  [key: string]: unknown;
}

export interface TagPromptRequest {
  commit_id: string;
  tags: string[];
}

export interface TagPromptResponse {
  commit_id: string;
}

export interface TraceEvaluationRun {
  id?: string | null | null;
  project_id: string;
  eval_name: string;
  model?: string | null | null;
  created_at?: string | null | null;
  user_id?: string | null;
  scorers?: Record<string, unknown>[] | null | null;
  custom_scorers: BaseScorer[];
  judgment_scorers: ScorerConfig[];
  trace_and_span_ids: Record<string, unknown>[][];
  is_offline: boolean;
  is_behavior: boolean;
}

export interface TraceInfo {
  trace_id: string;
  span_id: string;
}

export interface TraceScoringResult {
  scorers_data: Record<string, unknown>[];
  name?: string | null;
  data_object: TraceSpan;
  trace_id?: string | null;
  run_duration?: number | null;
  evaluation_cost?: number | null;
}

export interface TraceSpan {
  organization_id: string;
  project_id: string;
  user_id: string;
  timestamp: string;
  trace_id: string;
  span_id: string;
  parent_span_id: string | null;
  trace_state: string | null;
  span_name: string | null;
  span_kind: string | null;
  service_name: string | null;
  resource_attributes: Record<string, unknown>;
  span_attributes: Record<string, unknown>;
  duration: string;
  status_code: number;
  status_message: string | null;
  events: Record<string, unknown>[];
  links: string | null;
}

export interface TriggerRootSpanRulesRequest {
  traces: TraceInfo[];
}

export interface TriggerRootSpanRulesResponse {
  success: boolean;
  queued_traces: number;
}

export interface UntagPromptRequest {
  tags: string[];
}

export interface UntagPromptResponse {
  commit_ids: string[];
}

export interface UploadCustomScorerRequest {
  scorer_name: string;
  scorer_code: string;
  requirements_text: string;
  class_name: string;
  overwrite: boolean;
  scorer_type?: string | null;
  response_type: string;
  version?: number | null;
}

export interface UploadCustomScorerResponse {
  scorer_name: string;
  status: string;
  message: string;
}

export interface WelcomeResponse {
  [key: string]: unknown;
}
