/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export type BaseScorer = {
  score_type: string;
  threshold?: number;
  name?: (string | null);
  class_name?: (string | null);
  score?: (number | null);
  score_breakdown?: (Record<string, any> | null);
  reason?: (string | null);
  using_native_model?: (boolean | null);
  success?: (boolean | null);
  model?: (string | null);
  model_client?: (any | null);
  strict_mode?: boolean;
  error?: (string | null);
  additional_metadata?: (Record<string, any> | null);
  user?: (string | null);
  server_hosted?: boolean;
};