// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface BaseScorer {
  score_type: string;
  name: string;
  class_name?: string | null;
  score?: number | null;
  minimum_score_range?: number | null;
  maximum_score_range?: number | null;
  score_breakdown?: Record<string, unknown> | null;
  reason?: (string | Record<string, unknown>) | null;
  success?: boolean | null;
  model?: string | null;
  error?: string | null;
  additional_metadata?: Record<string, unknown> | null;
  user?: string | null;
  server_hosted?: boolean | null;
  using_native_model?: boolean | null;
  required_params?: string[] | null;
  strict_mode?: boolean | null;
}
