// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface CreateTestRunRequest {
  test_config_id: string;
  dataset_version_id?: string | null;
  dataset_version_number?: number | null;
  judge_versions?: {
    judge_id?: string | null;
    name?: string | null;
    tag?: string | null;
    version?: string | null;
    major_version?: number | null;
    minor_version?: number | null;
  }[];
  source?: string | null;
  agent_traces?:
    | { example_id: string; agent_offline_trace_id: string }[]
    | null;
}
