// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface CreateOfflineDatasetResponse {
  detail: string;
  dataset_id: string;
  dataset: {
    dataset_id: string;
    organization_id?: string | null;
    project_id?: string | null;
    name: string;
    schema?: Record<string, unknown> | null;
    current_version?: number | null;
    created_at?: string | null;
    updated_at?: string | null;
    creator_id: string | null;
    entries?: number | null;
    test_config_count?: number | null;
  };
}
