// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface CreateTestConfigRequest {
  name: string;
  description?: string | null;
  dataset_id?: string | null;
  dataset_name?: string | null;
  judge_ids?: string[] | null;
  judges?: { judge_id?: string | null; name?: string | null }[];
}
