// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface CreateOfflineDatasetRequest {
  name: string;
  schema: Record<string, unknown>;
  examples?: Record<string, unknown>[] | null;
  overwrite?: boolean | null;
  dataset_kind?: string | null;
  metadata?: Record<string, unknown> | null;
}
