// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { Example } from "./Example";

export interface CreateDatasetRequest {
  name: string;
  dataset_kind: string;
  examples: Example[];
  overwrite: boolean;
}
