// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface CreateExternalJudgeInput {
  name: string;
  judgeDescription?: string | null;
  judgeType: string;
  config?: Record<string, unknown> | null;
  initialVersion:
    | { scoreType: string; advancedSettings?: Record<string, unknown> | null }
    | {
        scoreType: string;
        advancedSettings?: Record<string, unknown> | null;
        outputs: { name: string; description: string }[];
      };
}
