// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface DatasetInfo {
  dataset_id: string;
  name: string;
  created_at: string;
  kind: string;
  entries: number;
  creator: string;
}
