// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { E2ETracesPerProjectRow } from "./E2ETracesPerProjectRow";

export interface E2ETracesPerProjectResponse {
  data: E2ETracesPerProjectRow;
  total_spans: number;
  total_traces: number;
  limit: number;
  offset: number;
}
