/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export type EvalResultsFetch = {
  experiment_run_id: string;
  project_name: string;
};
