/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

import { ScoringResult } from "./ScoringResult";

export interface EvalResultsFetchResponse {
  results: Array<ScoringResult>;
  ui_results_url: string;
}
