/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

import { ExampleEvaluationRun } from "./ExampleEvaluationRun";
import { ScoringResult } from "./ScoringResult";
import { TraceEvaluationRun } from "./TraceEvaluationRun";

export type EvalResults = {
  results: Array<ScoringResult>;
  run: ExampleEvaluationRun | TraceEvaluationRun;
};
