/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export type Example = {
  example_id?: string;
  created_at?: string;
  name?: string | null;
};
