// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { Example } from "./Example";

export interface ExampleScoringResult {
  scorers_data: Record<string, unknown>[];
  name?: string | null;
  data_object: Example;
  trace_id?: string | null;
  run_duration?: number | null;
  evaluation_cost?: number | null;
}
