// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { CustomScorerPayload } from "./CustomScorerPayload";
import type { Example } from "./Example";
import type { JudgmentScorerConfig } from "./JudgmentScorerConfig";

export interface ExampleEvaluationRun {
  id?: string | null;
  project_id: string;
  eval_name: string;
  model?: string | null;
  created_at?: string | null;
  user_id?: string | null;
  scorers?: Record<string, unknown>[] | null;
  custom_scorers: CustomScorerPayload[];
  judgment_scorers: JudgmentScorerConfig[];
  examples: Example[];
  trace_span_id?: string | null;
  trace_id?: string | null;
}
