// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface Example {
  example_id: string;
  created_at: string;
  name?: string | null;
  trace_id?: string | null;
  span_id?: string | null;
  offline_trace_id?: string | null;
  agent_offline_trace_id?: string | null;
}
