/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

import { BaseScorer } from "./BaseScorer";
import { Example } from "./Example";
import { ScorerConfig } from "./ScorerConfig";

export type ExampleEvaluationRun = {
  id?: string;
  project_name: string;
  eval_name: string;
  custom_scorers?: Array<BaseScorer>;
  judgment_scorers?: Array<ScorerConfig>;
  model: string;
  created_at?: string;
  examples: Array<Example>;
  trace_span_id?: string | null;
  trace_id?: string | null;
};
