// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { BaseScorer } from "./BaseScorer";
import type { Example } from "./Example";
import type { ScorerConfig } from "./ScorerConfig";

export interface ExampleEvaluationRun {
  id?: string | null;
  project_id: string;
  eval_name: string;
  model?: string | null;
  created_at?: string | null;
  user_id?: string | null;
  scorers?: Record<string, unknown>[] | null;
  custom_scorers: BaseScorer[];
  judgment_scorers: ScorerConfig[];
  examples: Example[];
  trace_span_id?: string | null;
  trace_id?: string | null;
}
