// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { ExperimentScorer } from "./ExperimentScorer";

export interface ExperimentRunItem {
  organization_id: string;
  experiment_run_id: string;
  example_id: string;
  data: Record<string, unknown>;
  name: string | null;
  created_at: string;
  scorers: ExperimentScorer[];
}
