// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface ExperimentScorer {
  scorer_data_id: string;
  name: string;
  score: number;
  success: number;
  reason: string | null;
  evaluation_model: string | null;
  threshold: number;
  created_at: string;
  error: string | null;
  additional_metadata: Record<string, unknown> | null;
  minimum_score_range: number;
  maximum_score_range: number;
}
