/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export interface FetchExperimentRunResponse {
  results?: Array<any> | null;
  ui_results_url?: string | null;
}
