// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { PromptScorer } from "./PromptScorer";

export interface FetchPromptScorersResponse {
  scorers: PromptScorer[];
}
