/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

import { PromptScorer } from "./PromptScorer";

export type FetchPromptScorerResponse = {
  scorer: PromptScorer;
};
