// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { ExperimentRunItem } from "./ExperimentRunItem";
import type { ExperimentScorer } from "./ExperimentScorer";

export interface FetchExperimentRunResponse {
  results: ExperimentRunItem[] | null;
  ui_results_url: string | null;
}
