// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { PromptCommitInfo } from "./PromptCommitInfo";

export interface GetPromptVersionsResponse {
  versions: PromptCommitInfo[];
}
