// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { Example } from "./Example";

export interface JudgeEvaluationRun {
  id?: string | null;
  eval_name: string;
  created_at?: string | null;
  judges: { name: string }[];
  examples: Example[];
  is_offline: boolean;
  is_behavior: boolean;
}
