// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { Example } from "./Example";

export interface LocalScorerResult {
  scorers_data: Record<string, unknown>[];
  data_object: Example;
}
