// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { BaseScorer } from "./BaseScorer";
import type { Example } from "./Example";
import type { ExampleEvaluationRun } from "./ExampleEvaluationRun";
import type { ExampleScoringResult } from "./ExampleScoringResult";
import type { ScorerConfig } from "./ScorerConfig";
import type { ScoringResult } from "./ScoringResult";
import type { TraceScoringResult } from "./TraceScoringResult";
import type { TraceSpan } from "./TraceSpan";

export interface LogEvalResultsRequest {
  results: ScoringResult[];
  run: ExampleEvaluationRun;
}
