// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { CustomScorerPayload } from "./CustomScorerPayload";
import type { Example } from "./Example";
import type { ExampleEvaluationRun } from "./ExampleEvaluationRun";
import type { JudgmentScorerConfig } from "./JudgmentScorerConfig";
import type { LocalScorerResult } from "./LocalScorerResult";

export interface LogEvalResultsExamplesRequest {
  results: LocalScorerResult[];
  run: ExampleEvaluationRun;
}
