// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { BaseScorer } from "./BaseScorer";
import type { Example } from "./Example";
import type { ExampleEvaluationRun } from "./ExampleEvaluationRun";
import type { LocalScorerResult } from "./LocalScorerResult";
import type { ScorerConfig } from "./ScorerConfig";

export interface LogEvalResultsExamplesRequest {
  results: LocalScorerResult[];
  run: ExampleEvaluationRun;
}
