// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { CustomScorerPayload } from "./CustomScorerPayload";
import type { Example } from "./Example";
import type { ExampleEvaluationRun } from "./ExampleEvaluationRun";
import type { ExampleScoringResult } from "./ExampleScoringResult";
import type { JudgmentScorerConfig } from "./JudgmentScorerConfig";
import type { ScoringResult } from "./ScoringResult";
import type { TraceScoringResult } from "./TraceScoringResult";
import type { TraceSpan } from "./TraceSpan";

export interface LogEvalResultsRequest {
  results: ScoringResult[];
  run: ExampleEvaluationRun;
}
