// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { BaseScorer } from "./BaseScorer";
import type { Example } from "./Example";
import type { ExampleEvaluationRun } from "./ExampleEvaluationRun";
import type { OfflineTestsLocalScorerResult } from "./OfflineTestsLocalScorerResult";
import type { ScorerConfig } from "./ScorerConfig";

export interface OfflineTestsLogEvalResultsExamplesRequest {
  results: OfflineTestsLocalScorerResult[];
  run: ExampleEvaluationRun;
}
