// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface OfflineDatasetVersionsResponse {
  versions: {
    version_id: string;
    dataset_id: string;
    organization_id: string;
    project_id: string;
    version_number: number;
    created_at: string;
    user_id: string | null;
    item_count: number;
  }[];
}
