// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface OfflineDatasetPageResponse {
  dataset: {
    dataset_id: string;
    organization_id?: string | null;
    project_id?: string | null;
    name: string;
    schema?: Record<string, unknown> | null;
    current_version?: number | null;
    created_at?: string | null;
    updated_at?: string | null;
    creator_id: string | null;
    entries?: number | null;
    test_config_count?: number | null;
  };
  entries: {
    item: {
      id: string;
      organization_id: string;
      project_id: string;
      dataset_id: string;
      version_added: number;
      example_id: string;
      created_at: string;
      user_id: string;
    };
    example: {
      example_id: string;
      organization_id?: string | null;
      project_id?: string | null;
      data: Record<string, unknown>;
      metadata?: Record<string, unknown> | null;
      created_at?: string | null;
      user_id: string;
    };
  }[];
  metadata: {
    hasMore: boolean;
    nextCursor: { created_at: string; example_id: string } | null;
  };
}
