// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface PreparedTestRunResponse {
  test_run: {
    id: string;
    organization_id?: string | null;
    project_id: string;
    user_id: string;
    test_config_id: string;
    dataset_id: string;
    dataset_version_id: string;
    source: string;
    status: string;
    name: string;
    error_message?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
    started_at?: string | null;
    completed_at?: string | null;
  };
  dataset: {
    dataset_id: string;
    organization_id?: string | null;
    project_id?: string | null;
    name: string;
    schema?: Record<string, unknown> | null;
    current_version?: number | null;
    created_at?: string | null;
    updated_at?: string | null;
    creator_id: string | null;
    entries?: number | null;
    test_config_count?: number | null;
  };
  dataset_version: {
    version_id: string;
    dataset_id: string;
    organization_id: string;
    project_id: string;
    version_number: number;
    created_at: string;
    user_id: string | null;
    item_count: number;
  };
  examples: {
    example_id: string;
    organization_id?: string | null;
    project_id?: string | null;
    data: Record<string, unknown>;
    metadata?: Record<string, unknown> | null;
    created_at?: string | null;
    user_id: string;
  }[];
  judges: {
    judge_id: string;
    judge_name: string;
    judge_type: string;
    score_type: string;
    judge_major_version: number;
    judge_minor_version: number;
  }[];
  evaluation_runs: {
    run_id: string;
    judge_name: string;
    example_id: string;
    test_run_id: string;
    judge_id: string;
    judge_major_version: number;
    judge_minor_version: number;
  }[];
  ui_results_url: string;
}
