/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export type PromptScorer = {
  name: string;
  prompt: string;
  threshold: number;
  options?: (Record<string, number> | null);
  created_at?: (string | null);
  updated_at?: (string | null);
  is_trace?: (boolean | null);
};