// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface PromptCommitInfo {
  name: string;
  prompt: string;
  tags: string[];
  commit_id: string;
  parent_commit_id: string | null;
  created_at: string;
  first_name: string;
  last_name: string;
  user_email: string;
}
