/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export interface PromptScorer {
  id: string;
  user_id: string;
  organization_id: string;
  name: string;
  prompt: string;
  threshold: number;
  model?: string;
  options?: Record<string, number> | null;
  description?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  is_trace?: boolean | null;
  is_bucket_rubric?: boolean | null;
}
