// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface PullOfflineDatasetResponse {
  dataset_id: string;
  organization_id?: string | null;
  project_id?: string | null;
  name: string;
  schema?: Record<string, unknown> | null;
  current_version?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
  creator_id: string | null;
  entries?: number | null;
  test_config_count?: number | null;
  dataset_kind: string;
  examples: {
    example_id: string;
    organization_id?: string | null;
    project_id?: string | null;
    data: Record<string, unknown>;
    metadata?: Record<string, unknown> | null;
    created_at?: string | null;
    user_id: string;
  }[];
}
