// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { Example } from "./Example";

export interface PullDatasetResponse {
  name: string;
  project_id: string;
  dataset_kind: string;
  examples: Example[];
}
