/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

import { PromptScorer } from "./PromptScorer";

export interface SavePromptScorerResponse {
  scorer_response: PromptScorer;
}
