/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export type SavePromptScorerRequest = {
  name: string;
  prompt: string;
  threshold: number;
  options?: Record<string, number> | null;
  is_trace?: boolean | null;
};
