/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export interface SavePromptScorerRequest {
  name: string;
  prompt: string;
  threshold: number;
  model?: string;
  is_trace?: boolean;
  options?: Record<string, number> | null;
  description?: string | null;
}
