// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { Example } from "./Example";
import type { ExampleScoringResult } from "./ExampleScoringResult";
import type { TraceScoringResult } from "./TraceScoringResult";
import type { TraceSpan } from "./TraceSpan";

export interface ScoringResult {
  [key: string]: unknown;
}
