/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export type ScorerConfig = {
  score_type: string;
  name?: string | null;
  threshold?: number;
  strict_mode?: boolean;
  required_params?: Array<string>;
  kwargs?: Record<string, any> | null;
};
