/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export type ScorerData = {
  name: string;
  threshold: number;
  success: boolean;
  score?: (number | null);
  reason?: (string | null);
  strict_mode?: (boolean | null);
  evaluation_model?: (Array<string> | string);
  error?: (string | null);
  additional_metadata?: (Record<string, any> | null);
};