/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

export type ScorerData = {
  id?: string;
  name: string;
  threshold: number;
  success: boolean;
  score?: number | null;
  reason?: string | null;
  strict_mode?: boolean | null;
  evaluation_model?: string | null;
  error?: string | null;
  additional_metadata?: Record<string, any> | null;
};
