// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface ScorerConfig {
  score_type?: string | null;
  name: string;
  model?: string | null;
  required_params?: string[] | null;
  kwargs?: Record<string, unknown> | null;
  result_type?: string | null;
}
