// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface TestRunItemsResponse {
  results: {
    organization_id: string;
    project_id: string;
    test_run_id: string;
    dataset_id: string;
    dataset_version_id: string;
    example_id: string;
    agent_offline_trace_id: string | null;
    created_at: string;
    example: {
      example_id: string;
      organization_id?: string | null;
      project_id?: string | null;
      data: Record<string, unknown>;
      metadata?: Record<string, unknown> | null;
      created_at?: string | null;
      user_id: string;
    } | null;
    data: Record<string, unknown>;
    scorers: {
      judge_id: string;
      judge_name: string | null;
      judge_major_version: number;
      judge_minor_version: number;
      score_type: string;
      num_value: number;
      bool_value: boolean;
      str_value: string;
      reason: Record<string, unknown>;
      metadata: Record<string, unknown>;
      success: boolean | null;
      error: string | null;
      created_at: string;
    }[];
  }[];
  has_more: boolean;
  next_cursor: string | null;
  ui_results_url?: string | null;
}
