// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface TestRunsResponse {
  test_runs: {
    id: string;
    organization_id?: string | null;
    project_id: string;
    user_id: string;
    test_config_id: string;
    dataset_id: string;
    dataset_version_id: string;
    source: string;
    status: string;
    error_message?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
    started_at?: string | null;
    completed_at?: string | null;
  }[];
}
