// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface TestConfigResponse {
  test_config: {
    id: string;
    organization_id?: string | null;
    project_id: string;
    dataset_id: string;
    name: string;
    description?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
    user_id: string;
    judges?: {
      id?: string | null;
      organization_id?: string | null;
      project_id?: string | null;
      test_config_id?: string | null;
      judge_id: string;
      created_at?: string | null;
      user_id: string;
      judge?: {
        id: string;
        name: string;
        judge_type: string;
        score_type: string;
      } | null;
    }[];
  };
}
