/**
 * Auto-generated by scripts/generate-client.ts
 * DO NOT EDIT MANUALLY - This file is generated automatically
 */

import { BaseScorer } from "./BaseScorer";
import { ScorerConfig } from "./ScorerConfig";

export interface TraceEvaluationRun {
  id?: string;
  project_name: string;
  eval_name: string;
  custom_scorers?: Array<BaseScorer>;
  judgment_scorers?: Array<ScorerConfig>;
  model?: string | null;
  created_at?: string;
  trace_and_span_ids: Array<[string, string]>;
  is_offline?: boolean;
  is_bucket_run?: boolean;
}
