// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { TraceSpan } from "./TraceSpan";

export interface TraceScoringResult {
  scorers_data: Record<string, unknown>[];
  name?: string | null;
  data_object: TraceSpan;
  trace_id?: string | null;
  run_duration?: number | null;
  evaluation_cost?: number | null;
}
