// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface TraceSpan {
  organization_id: string;
  project_id: string;
  user_id: string;
  timestamp: string;
  trace_id: string;
  span_id: string;
  parent_span_id: string | null;
  trace_state: string | null;
  span_name: string | null;
  span_kind: string | null;
  service_name: string | null;
  resource_attributes: Record<string, unknown>;
  span_attributes: Record<string, unknown>;
  duration: string;
  status_code: number;
  status_message: string | null;
  events: {
    Timestamp: string;
    Name: string;
    Attributes: Record<string, unknown>;
  }[];
  links: string | null;
}
