// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { CustomScorerPayload } from "./CustomScorerPayload";
import type { JudgmentScorerConfig } from "./JudgmentScorerConfig";

export interface TraceEvaluationRun {
  id?: string | null | null;
  project_id: string;
  eval_name: string;
  model?: string | null | null;
  created_at?: string | null | null;
  user_id?: string | null;
  scorers?: Record<string, unknown>[] | null | null;
  custom_scorers: CustomScorerPayload[];
  judgment_scorers: JudgmentScorerConfig[];
  trace_and_span_ids: Record<string, unknown>[][];
  is_offline: boolean;
  is_behavior: boolean;
}
