// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

export interface UploadCustomScorerRequest {
  scorer_name: string;
  scorer_code: string;
  requirements_text: string;
  class_name: string;
  overwrite: boolean;
  scorer_type?: string | null;
  response_type: string;
  version?: number | null;
}
