// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import type { UploadCustomScorerBundleMetadata } from "./UploadCustomScorerBundleMetadata";

export interface UploadCustomScorerBundleRequest {
  metadata: UploadCustomScorerBundleMetadata;
  bundle: string;
}
