name: Create new Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run check

      - name: Build package
        run: npm run build

      - name: Check for version bump
        id: version-check
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          # Try to get npm version, if package doesn't exist, treat as 0.0.0
          if NPM_VERSION=$(npm view judgeval version 2>/dev/null); then
            echo "npm_version=$NPM_VERSION" >> $GITHUB_OUTPUT
            echo "Found published version: $NPM_VERSION"
          else
            NPM_VERSION="0.0.0"
            echo "npm_version=$NPM_VERSION" >> $GITHUB_OUTPUT
            echo "Package not found on npm, treating as 0.0.0"
          fi

          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          if [ "$CURRENT_VERSION" != "$NPM_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "Version bumped from $NPM_VERSION to $CURRENT_VERSION"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Version $CURRENT_VERSION already published to npm"
            exit 1
          fi

      - name: Create Release
        if: steps.version-check.outputs.version_changed == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version-check.outputs.current_version }}
          release_name: Release v${{ steps.version-check.outputs.current_version }}
          body: |
            ## Changes in v${{ steps.version-check.outputs.current_version }}

            This release was automatically created due to a version bump in package.json.

            ### Version Changes
            - Previous: ${{ steps.version-check.outputs.npm_version }}
            - Current: ${{ steps.version-check.outputs.current_version }}
          draft: false
          prerelease: false

      - name: Create release package
        if: steps.version-check.outputs.version_changed == 'true'
        run: zip -r judgeval-v${{ steps.version-check.outputs.current_version }}.zip dist/

      - name: Upload Release Assets
        if: steps.version-check.outputs.version_changed == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./judgeval-v${{ steps.version-check.outputs.current_version }}.zip
          asset_name: judgeval-v${{ steps.version-check.outputs.current_version }}.zip
          asset_content_type: application/zip
